SELECT * FROM MEMBER;

SELECT COUNT(MEMBER.ID)
FROM MEMBER;

SELECT COUNT(MEMBER.PWD)
FROM MEMBER;

SELECT COUNT(MEMBER.RCMD_MEMBER_ID), COUNT(MEMBER.PWD)
FROM MEMBER;

SELECT COUNT(MEMBER.TYPE)
FROM MEMBER;

SELECT COUNT(*) -- 전체 검사를 진행하면 메모리를 많이 사용할 수 있다.
FROM MEMBER; -- 가능하면 식별자를 통해서 개수를 세는 것이 좋다.

-- 그룹바이
SELECT
        TYPE,
        COUNT(ID) AS COUNT
FROM MEMBER
GROUP BY TYPE;