CREATE TABLE MENU
(
    ID            NUMBER,
    KOR_NAME      NVARCHAR2(500),
    ENG_NAME      VARCHAR2(500),
    PRICE         NUMBER,
    IMG           VARCHAR2(200),
    REG_DATE      TIMESTAMP(6),
    CATEGORY_ID   NUMBER,
    REG_MEMBER_ID NUMBER
);

-- INNER JOIN 예시
SELECT
    M.*,
    C.NAME AS CATEGORY_NAME,
    MI.SRC AS IMG
FROM MENU M
    LEFT JOIN (SELECT * FROM MENU_IMAGE WHERE DEFAULT_IMG = 1) MI
    ON M.ID = MI.MENU_ID
JOIN CATEGORY C
    ON M.CATEGORY_ID = C.ID;

-- INNER JOIN 예시
SELECT *
FROM MENU
INNER JOIN (
    SELECT *
    FROM MENU_IMAGE
    WHERE DEFAULT_IMG = 1
) MI
ON MENU.ID = MI.MENU_ID;

-- VIEW 실행
SELECT * FROM MENU_VIEW;

-- 1. 형태소 분석
-- 2. 구문 분석
-- 3. 실행계획
-- 4. 번역 (컴파일) < 뷰는 여기부터 실행
-- 5. 실행

-- 시퀀스 생성하고 아이디 값을 지정하자


-- 시퀀스
CREATE SEQUENCE MENU_SEQ_TEST;
SELECT MENU_ID_SEQUENCE.NEXTVAL FROM DUAL;

INSERT INTO MENU (ID, KOR_NAME, ENG_NAME, PRICE, IMG, REG_DATE, CATEGORY_ID, REG_MEMBER_ID)
VALUES (MENU_SEQ_TEST.NEXTVAL, '테스트', 'TEST', 1000, 'test.jpg', SYSDATE, 1, 1);

-- 셀프 조인

SELECT * FROM MEMBER;

SELECT
    M.*,
    MR.NICKNAME AS RCMD_MEMBER_NICKNAME
FROM (SELECT * FROM MEMBER WHERE ID = 5) M
LEFT JOIN MEMBER MR
ON M.RCMD_MEMBER_ID = MR.ID;

-- 크로스 조인
-- 절대 하지 말아라!!!

-- 정렬
SELECT *
FROM MENU
ORDER BY REG_DATE DESC;

-- 함수가 존재 한다.
