spring:
  application:
    name: demo
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//hi.newlecture.com:1521/XEPDB1
    username: rland
    password: 1128
  servlet:
    multipart:
      max-file-size: 100MB # 파일 최대 크기
      max-request-size: 300MB # 요청 최대 크기

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  type-aliases-package: com.example.boot3.demo.entity # Entity 클래스가 있는 패키지

logging:
  level:
    com.example.boot3.demo.repository: trace


server:
  port: 80