spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 111
    url: jdbc:h2:mem:test&useUnicode=true&characterEncoding=utf8

  sql:
    init:
      encoding: utf-8

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true