
-- 8번 문제
SELECT
    M.ID,
    M.KOR_NAME,
    M.ENG_NAME,
    MR.NICKNAME AS REG_MEMBER_NAME
FROM MENU M
LEFT JOIN MEMBER MR
ON M.REG_MEMBER_ID = MR.ID;

-- 9번 문제
SELECT
    M.ID,
    M.KOR_NAME,
    M.ENG_NAME,
    MR.NICKNAME AS REG_MEMBER_NAME
FROM (SELECT * FROM MENU WHERE REG_DATE < '2024-08-01') M
LEFT JOIN MEMBER MR
    ON M.REG_MEMBER_ID = MR.ID;

-- 10번 문제
SELECT
    C.ID,
    C.NAME,
    NVL(M.COUNT, 0) AS MENU_COUNT
FROM CATEGORY C
LEFT JOIN (
    SELECT CATEGORY_ID, COUNT(ID) AS COUNT
    FROM MENU
    GROUP BY CATEGORY_ID
) M
ON C.ID = M.CATEGORY_ID;

-- 11번 문제
SELECT
    C.ID,
    C.NAME,
    NVL(M.COUNT, 0) AS MENU_COUNT
FROM CATEGORY C
JOIN (
    SELECT CATEGORY_ID, COUNT(ID) AS COUNT
    FROM MENU
    GROUP BY CATEGORY_ID
    HAVING COUNT(ID) < 3
) M
ON C.ID = M.CATEGORY_ID;

-- 12번 문제
SELECT * FROM MENU
WHERE CATEGORY_ID IN (1, 4);

-- 13번 문제 (유니온 문제)

SELECT
    C.ID,
    C.NAME,
    NVL(M.COUNT, 0) AS MENU_COUNT
FROM CATEGORY C
         JOIN (
    SELECT CATEGORY_ID, COUNT(ID) AS COUNT
    FROM MENU
    GROUP BY CATEGORY_ID
    HAVING COUNT(ID) = 3
) M
ON C.ID = M.CATEGORY_ID
UNION ALL
SELECT
    C.ID,
    C.NAME,
    NVL(M.COUNT, 0) AS MENU_COUNT
FROM CATEGORY C
         LEFT JOIN (
    SELECT CATEGORY_ID, COUNT(ID) AS COUNT
    FROM MENU
    GROUP BY CATEGORY_ID
) M
ON C.ID = M.CATEGORY_ID